"use client";
export const runtime="edge";
import{useState}from"react";import{useRouter}from"next/navigation";import Link from"next/link";import{ArrowLeft,UserPlus}from"lucide-react";import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";import{Label}from"@/components/ui/label";import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from"@/components/ui/select";import{toast}from"@/hooks/use-toast";
const ROLES=[{value:"STAFF",label:"Staff"},{value:"SUPERVISOR",label:"Supervisor"},{value:"MANAGER",label:"Manager"},{value:"FRANCHISE",label:"Franchise"},{value:"CEO",label:"CEO"}];
export default function NewUserPage(){
  const router=useRouter();const[loading,setLoading]=useState(false);
  const[form,setForm]=useState({name:"",email:"",password:"",role:"STAFF",hotelId:"",territoryId:"",commissionRate:"0.10"});
  function set(f:string,v:string){setForm(p=>({...p,[f]:v}));}
  async function handleSubmit(e:React.FormEvent){e.preventDefault();if(!form.name||!form.email||!form.password){toast({title:"Missing fields",variant:"destructive"});return;}setLoading(true);try{const res=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name,email:form.email,password:form.password,role:form.role,hotelId:form.hotelId||undefined,territoryId:form.territoryId||undefined,commissionRate:parseFloat(form.commissionRate)||0.10})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Failed");toast({title:"User created"});router.push("/admin/users");}catch(err:any){toast({title:"Error",description:err.message,variant:"destructive"});}finally{setLoading(false);}}
  return(<div className="max-w-2xl space-y-6"><div className="flex items-center gap-4 mb-8"><Link href="/admin/users"><Button variant="ghost" size="icon"><ArrowLeft className="h-4 w-4"/></Button></Link><h1 className="text-2xl font-bold"><UserPlus className="h-6 w-6 text-amber-400 inline mr-2"/>New User</h1></div><form onSubmit={handleSubmit} className="space-y-4"><Card className="bg-gray-900 border-gray-800"><CardHeader><CardTitle>Identity</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><Label>Full Name *</Label><Input value={form.name} onChange={e=>set("name",e.target.value)} className="bg-gray-800"/></div><div><Label>Email *</Label><Input type="email" value={form.email} onChange={e=>set("email",e.target.value)} className="bg-gray-800"/></div></div><div><Label>Password *</Label><Input type="password" value={form.password} onChange={e=>set("password",e.target.value)} className="bg-gray-800"/></div></CardContent></Card><Card className="bg-gray-900 border-gray-800"><CardHeader><CardTitle>Role</CardTitle></CardHeader><CardContent><Select value={form.role} onValueChange={v=>set("role",v)}><SelectTrigger className="bg-gray-800"><SelectValue/></SelectTrigger><SelectContent className="bg-gray-800">{ROLES.map(r=>(<SelectItem key={r.value} value={r.value}>{r.label}</SelectItem>))}</SelectContent></Select></CardContent></Card><Button type="submit" disabled={loading} className="bg-amber-500 text-black">{loading?"Creating…":"Create User"}</Button></form></div>);
}
